### ISSUE TITLE
AutoModelForCausalLM fails on CPU do to bitsandbytes requirement

### ISSUE THREAD

**Issue by dansbecker** [RichardKelley/dendron#1]
I am trying to run a behavior tree using Dendron on a CPU-only system.

`bitsandbytes` is not well supported on CPU. So, transformers' `PreTrainedModel.from_pretrained` tries to validate that `bitsandbytes` is available whenever bnb_cfg is not None. It does so with [this function](https://github.com/huggingface/transformers/blob/main/src/transformers/utils/import_utils.py#L744-L752)

That function checks `torch.cuda.is_available`, which is False on CPU-only systems. The end result is an exception in `PreTrainedModel.from_pretrained`.

We can short-circuit this check by passing `bnb_config` as `None` to the pretrained model when we are not loading the model in 4bit or 8bit.

I am sending a PR with this one-line change.

**Comment by RichardKelley** [comment]
This looks sensible. I'm up against a writing deadline tonight, but I'll double check the PR and merge tomorrow. I suspect that there are a few other places in the library where a change like this will be helpful.

Thanks!

**Comment by RichardKelley** [comment]
@dansbecker I've merged your PR and copied the fix to the corresponding locations for ImageLMAction and CompletionCondition. Closing this issue for now. Thanks again!
